pr-yaml

diff --git a/stages/pr.yaml b/stages/pr.yaml
--- a/stages/pr.yaml
+++ b/stages/pr.yaml
@@ -16,24 +16,38 @@ stages:
 
     - template: ../steps/demo-init.yaml
     - bash: |
-          # Remember Exit Code
-          set -uo pipefail
+        # Remember Exit Code
+        set -uo pipefail
 
-          # Run `terraform plan` and save output (to be used later for posting to GitHub)
-          if terraform plan -detailed-exitcode -input=false -var-file=02-terraform.auto.tfvars -var="client_id=$ARM_CLIENT_ID" \
-              -var="client_secret=$ARM_CLIENT_SECRET" \
-              -var="tenant_id=$ARM_TENANT_ID" \
-              -var="subscription_id=$ARM_SUBSCRIPTION_ID" | tee plan-output.txt \
-              exit ${PIPESTATUS[0]}
-          then 
-            echo "No Configuration Drift deteced"
-            echo "##vso[task.setvariable variable=exitCode;isoutput=true]zero"
-          else 
-            tf_exit_code=$?
-            echo "Configuration Drift Detected" 
-            echo "##vso[task.setvariable variable=exitCode;isoutput=true]non-zero"
-            exit $tf_exit_code
-          fi
+        # Run `terraform plan` and save output (used later for posting to GitHub)
+        if terraform plan --input=false -var-file=02-terraform.auto.tfvars -var="client_id=$ARM_CLIENT_ID"  -var="client_secret=$ARM_CLIENT_SECRET" -var="tenant_id=$ARM_TENANT_ID"  -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
+            | tee plan-output.txt \
+            exit ${PIPESTATUS[0]}
+        then
+          echo "🟢 No configuration drift detected"
+          echo "##vso[task.setvariable variable=exitCode;isOutput=true]zero"
+        else
+          tf_exit_code=$?
+          echo "⚠️ Configuration drift detected"
+          echo "##vso[task.setvariable variable=exitCode;isOutput=true]non-zero"
+          exit $tf_exit_code
+        fi
+        
+          # # Run `terraform plan` and save output (to be used later for posting to GitHub)
+          # if terraform plan -detailed-exitcode -input=false -var-file=02-terraform.auto.tfvars -var="client_id=$ARM_CLIENT_ID" \
+          #     -var="client_secret=$ARM_CLIENT_SECRET" \
+          #     -var="tenant_id=$ARM_TENANT_ID" \
+          #     -var="subscription_id=$ARM_SUBSCRIPTION_ID" | tee plan-output.txt \
+          #     exit ${PIPESTATUS[0]}
+          # then 
+          #   echo "No Configuration Drift deteced"
+          #   echo "##vso[task.setvariable variable=exitCode;isoutput=true]zero"
+          # else 
+          #   tf_exit_code=$?
+          #   echo "Configuration Drift Detected" 
+          #   echo "##vso[task.setvariable variable=exitCode;isoutput=true]non-zero"
+          #   exit $tf_exit_code
+          # fi
       displayName: Terraform - Detect Configuration drift
       name: planStep
       env:
